### GET from TrialJectory
POST https://stage-webapi.trialjectory.com/mitreMatches
content-type: application/json; charset=UTF-8
user-agent: Clinical-Trial-Matching-Wrapper

  {
    "lat":"27.968062",
    "lng":"-82.479089",
    "distance":null,
    "biomarkers":[],
    "stage":null,
    "cancerName":"bladder",
    "cancerType":"squamous_cell_carcinoma",
    "cancerSubType":null,
    "ecog":null,
    "karnofsky":null,
    "medications":[],
    "procedures":[],
    "metastasis":[],
    "age":66
  }

### GET ClinicalTrials.gov study
GET https://clinicaltrials.gov/api/v2/studies/NCT03746431

### Carebox Auth Token
curl --request POST \
  --url https://stg-auth.emergingmed.com/oauth/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --header 'user-agent: cURL' \
  --data 'grant_type=client_credentials' \
  --data 'client_id={{cb_client_id}}' \
  --data 'client_secret={{cb_client_secret}}'

### GET From Carebox
POST https://stg-api.emergingmed.com/v2.1/trials/directMatch
content-type: application/json
Authorization: Bearer {{cb_token}}

  {
    "page": 1,
    "pageSize": 50,
    "fields": [
      "trialId",
      "nctId",
      "fullTitle",
      "shortTitle",
      "status",
      "phase",
      "sites",
      "overallContacts"
    ],
    "filter": {
      "condition": {
        "valueSetId": "2.16.840.1.113883.6.96",
        "valueId": "255108000"
      },
      "countries": ["US"],
      "eligibility": [
        { "fieldId": "6", "mode": "", "value": "01011988" },
        {
          "fieldId": "19",
          "mode": "",
          "values": [
            { "valueSetId": "2.16.840.1.113883.6.96", "valueId": "1162767002" }
          ]
        }
      ],
      "distance": {
          "distance": 20,
          "distanceUnit": "mi",
          "from": { "lat": 27.968062, "lon": -82.479089}
      }
    },
    # "sort": [{ "field": "distance", "order": "asc" }],
    "origin": { "from": { "lat": 27.968062, "lon": -82.479089 } }
  }

### GET CTS API
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
X-API-KEY: {{$processEnv CTS_V2_API_KEY}}

  {
    "nct_id": "NCT02674061",
    "include": [
      "outcome_measures"
    ],
    "size": 1
  }

### BCT.org
POST https://www.ctmatch.org/mitre-service-v1/services/bctmatch/bundle/trials
Content-Type: application/fhir+json

  {
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
      {
        "resource": {
          "resourceType": "Parameters",
          "id": "0",
          "parameter": [
            {
              "name": "zipCode",
              "valueString": "33606"
            },
            {
              "name": "travelRadius",
              "valueString": "20"
            }
          ]
        }
      },
      {
        "resource": {
          "resourceType": "Patient",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-patient"
            ]
          },
          "id": "llA6DTu6FA5gxmRcopqmH",
          "gender": "female",
          "birthDate": "1965"
        },
        "fullUrl": "urn:uuid:llA6DTu6FA5gxmRcopqmH"
      },
      {
        "resource": {
          "resourceType": "Condition",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-primary-cancer-condition"
            ]
          },
          "subject": {
            "reference": "urn:uuid:llA6DTu6FA5gxmRcopqmH",
            "type": "Patient"
          },
          "code": {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "254838004",
                "display": "Carcinoma of breast (disorder)"
              }
            ]
          },
          "category": [
            {
              "coding": [
                {
                  "system": "http://snomed.info/sct",
                  "code": "64572001"
                }
              ]
            }
          ]
        }
      }
    ]
  }

### GET CTS API
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
X-API-KEY: {{$processEnv CTS_V2_API_KEY}}

  {
    "nct_id": "NCT06814977",
    "include": [
      "nct_id",
      "current_trial_status",
      "study_protocol_type",
      "official_title",
      "primary_purpose",
      "phase",
      "diseases.is_lead_disease",
      "diseases.name",
      "diseases.inclusion_indicator",
      "diseases.nci_thesaurus_concept_id",
      "diseases.type",
      "sites.org_country",
      "sites.recruitment_status"
    ],
    "size": 1
  }

